name: amnh
title: "Collectionscope Demo: American Museum of Natural History"
titleFormatted: "Collection<strong>scope</strong> Demo"
description: "Explore the Museum’s collections across time and space."
introductionText: "There are <strong>9,369 anthropology objects</strong> on display at the <a href='https://amnh.org' target='_blank'>American Museum of Natural History</a>, but this is only <strong>2 percent</strong> of the Museum’s collections! Where were these objects collected? When were they collected? And why were they chosen? Let’s explore."
creditText: "The <a href='https://amnh-sciviz.github.io/collectionscope/' target='_blank'>CollectionScope Tool</a> is a part of the Knight Foundation's <a href='https://knightfoundation.org/press/releases/shaping-the-future-of-technology-in-museums-knight-invests-750000-in-five-experiments-using-immersive-technology-in-the-arts/' target='_blank'>Immersive Technology in the Arts Fund</a>"
credits:
  - name: "American Museum of Natural History"
    url: "https://amnh.org/"
    image: "../../img/amnh_logo.png"
  - name: "Knight Foundation"
    url: "https://knightfoundation.org/"
    image: "../../img/knight_logo.png"
metadataFile: "data/AMNH_Anthro_Objects_Consolidated.xlsx"

metadataFilterQuery: "Content != ''"

identifierColumn: "Content"
dateColumn: "Year"
dateLabel: "Year"
minimumYear: 1600
maximumYear: 2050
latitudeColumn: "Latitude"
longitudeColumn: "Longitude"
countryColumn: "Country"
baseMap: #"../../img/world_map_with_regions.png"
baseMapKey: #"../../img/world_map_key_with_regions.png"
groupByColumn: "Region"
groupLabel: "Region"
groupLimit: 8
showOtherGroup: true
otherLabel: "Other"
groupColors:
  - "#7aa030"
  - "#726aa4"
  - "#d37200"
  - "#d6a900"
  - "#529c99"
  - "#b13734"
  - "#1f3c90"
  - "#5a0661"
itemFields:
  - column: "Title"
    isTitle: true
  - column: "URL"
    label: "View item details"
    isLink: true
  - column: "ImageURL"
    isImage: true
  - column: "Catalog No"
    label: "Catalog Number"
  - column: "Year"
    label: "Year acquired"
  - column: "Type"
    label: "Type"
  - column: "Country"
    label: "Country of origin"
  - column: "Donor"
    label: "Donor"

visualizations:
  - name: "timelineTunnel"
    type: "timeline"
    config:
      minYear: 1600
      maxYear: 2050
  - name: "timelineTracks"
    type: "timeline"
    config:
      groupBy: "Country"
      sortBy: "count"
      sortOrder: "desc"
  - name: "geographyBars"
    type: "bars"
    config:
      center: [0, 0]
      zoom: 2
      maxZoom: 10
      minZoom: 1

imageDirectory: "path/to/images"
imageHasAlpha: false
defaultColor: "#3C3C3C"
filenameColumn: "filename"
noImageValue: "no_image.jpg"

labels:
  yearFontSize: 12
  groupFontSize: 10
  groupFontThickness: 0.1
  countryFontSize: 10
  countryFontThickness: 0.1

sounds:
  default:
    layout: "years"
    filenames: ["audio/audio1.mp3", "audio/audio2.mp3"]
    spriteDuration: 30
    db: -10
    reverb: 0.3
    quantities:
      - name: "low"
       
